comics_content = '//a[@class="fed-list-pics fed-lazy fed-part-2by3"]'
href_attribute = './@href'
chapter_name_content = './/span[@class="fed-list-remarks fed-font-xii fed-text-white fed-text-center"]/text()'
page_content = '//a[@class="fed-btns-info fed-rims-info"]'
content = './text()'
onclick_attribute = './@onclick'
comic_id_content = '//meta[@itemprop="url"]/@content'
comic_name_content = '//meta[@property="og:comic:book_name"]/@content'
comic_info_content = '//li[@class="fed-col-xs12 fed-col-md6 fed-part-eone website-padding-right-1"]'
span_content = './span/text()'
date_content = './a/text()'
chapters_content = '//a[@class="fed-btns-info fed-rims-info fed-part-eone"]'
script_content = '//script/text()'

